### ISSUE TITLE
Module "Webgriffe_InvoiceRequest" requires module "Webgriffe_TaxIdPro".

### ISSUE THREAD

**Issue by davidgv88** [webgriffe/invoice-request-extension#1]
When i install the module appears this error:

Module "Webgriffe_InvoiceRequest" requires module "Webgriffe_TaxIdPro".

#0 /Applications/MAMP/htdocs/magento19/app/code/core/Mage/Core/Model/Config.php(849): Mage::throwException('Module "Webgrif...')
#1 /Applications/MAMP/htdocs/magento19/app/code/core/Mage/Core/Model/Config.php(812): Mage_Core_Model_Config->_sortModuleDepends(Array)
#2 /Applications/MAMP/htdocs/magento19/app/code/core/Mage/Core/Model/Config.php(315): Mage_Core_Model_Config->_loadDeclaredModules()
#3 /Applications/MAMP/htdocs/magento19/app/code/core/Mage/Core/Model/App.php(425): Mage_Core_Model_Config->loadModules()
#4 /Applications/MAMP/htdocs/magento19/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#5 /Applications/MAMP/htdocs/magento19/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#6 /Applications/MAMP/htdocs/magento19/index.php(83): Mage::run('', 'store')
#7 {main}

**Comment by mmenozzi** [comment]
You're right, sorry. We'll upload the "Webgriffe_TaxIdPro" extension in a public GitHub repository soon.

**Comment by davidgv88** [comment]
Thanks!

**Comment by mmenozzi** [comment]
Hi @davidgv88,
as promised we released the Webgriffe_TaxIdPro extension here: https://github.com/webgriffe/taxidpro-extension

Please also note that the invoice-request-extension requires the user to enter some value in the additional fields provided by the taxid-pro-extension. I don't know if this suits your needs but in Italy to request an invoice you must provide data like tax identification number (if you're a private customer) or the VAT number (if you're a company).
